sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t abchow98/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abchow98/react-test npm test

after_success:
  - docker build -t abchow98/multi-client ./client
  - docker build -t abchow98/multi-nginx ./nginx
  - docker build -t abchow98/multi-server ./server
  - docker build -t abchow98/multi-worker ./worker
  # Login to Docker CLI

  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD" docker.io

  - docker push abchow98/multi-client
  - docker push abchow98/multi-nginx
  - docker push abchow98/multi-server
  - docker push abchow98/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-851129632067"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
